### ISSUE TITLE
[Request/Question] 

### ISSUE THREAD

**Issue by brunogaspar** [stevebauman/inventory#20]
Hello @stevebauman 

I'm looking into using your package, as it feels very complete, but one requirement, for me at least, is to have inventory tracking for products that have variants.

With the most common example, T-shirt with Colors and Sizes.

One way would be to have a `parent_id` column on the, in this case `inventories` table, and each `variant` would be a new product with it's parent being the root one, and the `parent_id` on the root product would be obviously `0`, makes sense? xD

How would you go about this with your package?

**Comment by stevebauman** [comment]
Hi, thanks for the question!

I definitely like this idea, and this is something that I have no doubt should be implemented, though managing variants would be tricky.  The only way to perform this now is by creating separate inventory items per variant, which is definitely not ideal.

Having a parent ID may be an easy solution to this, since they would still be located in the inventory table and would be able to be tracked individually.

Unfortunately though, this feature would fall after assemblies are implemented and finished, which might be a couple weeks away as I'm still in the process of finishing another project [Adldap2](github.com/Adldap2/Adldap2).

If you end up doing this yourself before I start working on it, definitely send a pull request, as this would be an awesome feature to have.

**Comment by brunogaspar** [comment]
Thanks @stevebauman , i'll see what i can "hack" around, and if i find it doable to be implemented on this package, i'll do a PR as a Proposal.

Hopefully someone else might chime in and give other ideas/implementations, but this is kinda how Amazon handles their products too with Parent / Child, where the Child is the variation.

> Probably a separate Products package with this functionality would be useful (haven't find one :()

**Comment by stevebauman** [comment]
Hey @brunogaspar, this functionality is being added today, closing this for now, thanks!
