### ISSUE TITLE
getSkuAttribute() issues

### ISSUE THREAD

**Issue by rawcreative** [stevebauman/inventory#8]
Currently getSkuAttribute() is called every time a model is booted since eloquent tries to cache the value of the attribute. So this means even if skus are disabled in the config the db is still being hit when the model is booted looking for the sku. The getSku method needs to check the config to see if skus are enabled to avoid this.

The other issue with this method is that it prevents eloquent from caching the query since getSku() is explicitly hitting the db each time it's called via $this->sku()-first(), even when the model has been eager loaded. 

After a quick look at the code, If getSkuAttribute() was removed and calls to $this->sku()->first() in the trait were shifted to $this->sku everything could be properly cached. Not sure if removing is possible since I didn't comb through it enough to see if there was a specific reason this method exists.

**Comment by stevebauman** [comment]
Good catch! I wasn't aware that eloquent cached relationship queries when using the attribute method like you've shown above. The only reason I used `$this->sku()->first()` was due to my tests failing when trying to call relationships by their dynamic attribute. I use this method for grabbing the metric from an inventory as well. I'll change these at the same time.

I'll also change `getSkuAttribute()` to something else, since this actually overrides the relationship method and like you said. Possibly `getSkuCodeAttribute()` so it can be accessed on the item by `$item->sku_code`.

I don't have access to my laptop at the moment, but if you submit a PR I can merge it in. If you're unable to I can fix this tomorrow morning.

Thanks!

**Comment by stevebauman** [comment]
Ok this caching issue is fixed in the next update. After lots of testing and playing around with using the actual model relationship attribute (such as `$item->sku`), I decided on using the `remember()` function on the `hasOne` queries that check if the relationship exists. For example on the `hasSku()` method:

    public function hasSku()
    {
        if($this->sku()->remember(1)->count() > 0) return true;

        return false;
    }

I've made sure that the database is only queried once upon first request, and then the cache is used afterwards.

For the `getSkuAttribute()`, I've renamed the method to `getSkuCodeAttribute()` so the sku will now be retrieved by using `$item->sku_code`, and the relationship will now be fully accessible using `$item->sku`. The `getSkuAttribute()` method returns the `getSku()` method, and I've made the cache change to this method as well so it will only be queried once.

    /**
     * Returns the item's SKU
     *
     * @return null|string
     */
    public function getSku()
    {
        if($this->hasSku())
        {
            $sku = $this->sku()->remember(1)->first();

            return $sku->code;
        }

        return NULL;
    }

Since I've renamed methods, I'll have to bump the release to `v1.4.*` to follow semantic versioning. It'll be released today with some other tweaks.

**Comment by stevebauman** [comment]
Never mind, scratch all of that caching information I just posted. After testing in Laravel 5 apparently the `remember()` method was removed due to caching being now independent from Eloquent. That's a drag... Going to have to use the cache manually it seems. I'll post an update when I have something going for both versions.

**Comment by stevebauman** [comment]
Ok fixed, it was my tests that were the issue. The methods now use the relationship attribute instead of a fresh query so you can use `with()` to prevent multiple queries. 29294a4420bd7d127a8ffc48921e3f26f092807e
