### ISSUE TITLE
Default Location

### ISSUE THREAD

**Issue by rawcreative** [stevebauman/inventory#9]
Something that came to mind is that having a default location could be valuable in certain situations. For instance, since stock currently has aisle/row/bin fields, it's not extremely likely that these would be created as locations. So locations would typically be used in more of a 'Warehouse A', 'Warehouse B' type situation. If that's the case and there is only 1 location, having to constantly query and pass the location for each stock add could be tedious. The same could be said for the assemblies, where in many cases the assemblies will be built from stock in one location the majority of the time (until you get into larger scale manufacturing situations). 

So maybe being able to specify a default location in config or setting it as a field on the location table could be useful. Then a method called `createStock()` could be added to the inventory trait which would in turn call `createStockOnLocation()` passing the default location.

Thoughts?

**Comment by stevebauman** [comment]
Hmm I like the idea.. Are you thinking of having a configuration value with the default location attributes to be created if a location doesn't exist already?

    //config.php
    'default_location' => array(
        'name' => 'Warehouse',
    ),

This would then be the location to use if a location wasn't provided, for an example of your api:

    //User API
    $item->createStock($quantity = 20);

    //InventoryTrait.php
    public function createStock($quantity = 20, $location = NULL, $aisle = NULL, $bin = NULL, $row = NULL)
    {
        if(!$location) $location = $this->getDefaultLocation();

        //create the stock
    }

Is that the idea you're going for?

If so, I'm not too sure... I understand it's more tedious grabbing a specific location every time you need to create a stock on an item (even more resource heavy due to querying a location every time), but I think being specific with the creation definitely helps you understand where the stock is actually being created when looking through the code, rather than letting the location be assumed.

In my specific case of using this inventory, I have more than 40+ locations, so this wouldn't help my scenario. However saying that, I don't see a bad reason on why it shouldn't be implemented, and leave it up to the developer to decide on their method...

**Comment by rawcreative** [comment]
I hadn't thought about creating a default if one didn't exist. Your example is basically what I was thinking. Since I can't really think of a good way to implement a default without adding overhead (another db call) or adding a 'default' column to the locations table, maybe just have getDefaultLocation() return the first location in the DB?. If the developer needs to change it they can just override the trait method in their model with whatever logic they require.

**Comment by stevebauman** [comment]
After some thoughts, I'm not too sure about this. I think if a developer wants default locations they should implement it on their end. I'd hate to add some sort of assumptions into this package and it cause headaches or issues down the line. I want to keep the inventory as absolute as possible.

If I added a default location on my end, developers who haven't read all the documentation might be confused as to why locations are being created behind the scenes.

You could simply add a `firstOrCreate()` method to the location model before trying to create a stock on a location. This would make sure at least some location exists. For example:

public function create()
{
    if( ! Input::get('location_name')) 
    {
        $location = Location::firstOrCreate(array(
            'name' => 'Default Location',
        ));
    } else
    {
        $location = Location::create(array(
            'name' => Input::get('location_name),
        ));
    }

    $quantity = Input::get('quantity');
    
    $item = Inventory::find(1);

    $item->createStockOnLocation($quantity, $location);
}

If this wasn't what you were going for, definitely feel free to re-open the issue and we can go from there. Thanks!

- Also, working on assemblies on the developer branch. If you're interested definitely have a look and let me know of your thoughts.

**Comment by rawcreative** [comment]
No worries, I've had a default location specified in my app all along, just figured it might be useful for others.
